#!/bin/bash 
########################################## 
#           Linux executable             #
##########################################

MAIN_ENTRY_POINT=src/main.py
ROOT=$(dirname -- "$( readlink -f -- "$0"; )");
FILE=$1;

if command -v python > /dev/null; then
    # file path reading disabled for testing defaults to the test.fbx file in the root. 
    #python $ROOT/$MAIN_ENTRY_POINT $FILE
    python $ROOT/$MAIN_ENTRY_POINT $ROOT/test.fbx
else
    echo "Python does not exist, install python using a package-manager and try again..."
fi    